---
- name: "Информация по дистрибутиву"
  debug:
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ ansible_distribution_major_version }}-{{ ansible_os_family }}-{{ ansible_system }}"

- name: "Подключение конфигураций разных ОС"
  ansible.builtin.include_vars: "{{ lookup('first_found', findme) }}"
  vars:
    findme:
      paths:
        - "vars"
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      skip: true

- name: "Подключение задач для разных ОС"
  ansible.builtin.include_tasks: "{{ lookup('first_found', findme) }}"
  vars:
    findme:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "failover.yml"
      skip: true
