# group_vars/all.yml
users:
  - username: devops
    pubkeys:
      - "ssh-rsa AAAA...key1"
      - "ssh-ed25519 AAAA...key2"
    additional_groups:
      - docker
      - developers
    sudo: true

  - username: analyst
    pubkeys:
      - "ssh-rsa AAAA...key3"
    additional_groups:
      - analytics
      - reports
    sudo: false

revocations:
  - username: olduser
    pubkeys:
      - "ssh-rsa AAAA...oldkey"

vendors:
  - username: vendor1
    pubkeys:
      - "ssh-rsa AAAA...vendorkey"
    additional_groups:
      - vendors